language: python
python:
  - '3.3'
install:
  - git clone https://github.com/suttacentral/suttacentral-text.git text
  - pip install --use-mirrors -r requirements.txt
before_script: 
  - mysql -e 'create database suttacentral;'
  - >
    echo -e "[mysql]\n    user: 'travis'\n    password: ''\n    db: 'suttacentral'" > local.conf
  - make reset-db
  - make server &
  - sleep 10
after_script: pkill -f server.py
script: PHANTOMJS=1 make test
