notifications:
  email:
    recipients:
      - suttacentral-dev@googlegroups.com
    on_success: change
    on_failure: always
language: python
python:
  - '3.3'
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - git clone https://github.com/suttacentral/suttacentral-data.git data
  - pip install --use-mirrors --download-cache $HOME/.pip-cache -r requirements.txt
before_script:
  - invoke travis.prepare
  - invoke assets.compile
  - invoke travis.start_server
script:
  - invoke dictionary.build
  - invoke search.index
  - invoke test.all --phantomjs
after_script:
  - invoke travis.stop_server
