notifications:
  email:
    recipients:
      - suttacentral-dev@googlegroups.com
    on_success: change
    on_failure: always
language: python
python:
  - '3.3'
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - git clone https://github.com/suttacentral/suttacentral-text.git text
  - pip install --use-mirrors --download-cache $HOME/.pip-cache -r requirements.txt
before_script:
  - mysql -e 'create database suttacentral;'
  - >
    echo -e "[mysql]\n    user: 'travis'\n    password: ''\n    db: 'suttacentral'" > local.conf
  - make reset-db
  - make server &
  - sleep 10
after_script: pkill -f server.py
script: PHANTOMJS=1 make test
